import type { CriterionId } from "@/locales/pt-BR";
import type { CriterionMeta } from "../types";

export const META_UI_PT: Record<CriterionId, CriterionMeta> = {
  passive_voice: {
    label: "Voz passiva",
    ruleId: "passive_voice",
    kind: "Construção sintática",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dotted",
    signal: "forma do verbo “ser” seguida de particípio, em palavras próximas",
    why: "Quem pratica a ação some ou vai para o fim da frase. Quando a construção descreve um estado, e não uma ação, não há agente a nomear: só o contexto decide.",
  },
  passiva_sintetica: {
    label: "Voz passiva sintética",
    ruleId: "passiva_sintetica",
    kind: "Construção sintática",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dotted",
    signal:
      "“se” depois do verbo (aplica-se, publicam-se) ou antes dele, logo após palavras como “não” e “que” (não se aplica); ficam de fora verbos que sempre levam “se” (trata-se, refere-se…)",
    why: "O “se” esconde quem pratica a ação, e o leitor precisa saber quem faz o quê.",
  },
  nominalization: {
    label: "Ação com verbo genérico",
    ruleId: "nominalization",
    kind: "Escolha lexical",
    principleName: "Frases claras e concisas",
    channel: "inline",
    markStyleClass: "mark-dashed",
    signal:
      "verbo de apoio (fazer, realizar, efetuar, proceder, promover) seguido de artigo ou preposição e de um substantivo que vem de um verbo, em palavras seguidas (“fazer a análise”)",
    why: "Esconde a ação dentro de um substantivo e alonga a frase sem necessidade.",
  },
  nominalizacao_encadeada: {
    label: "Ações escritas como substantivos",
    ruleId: "nominalizacao_encadeada",
    kind: "Escolha lexical",
    principleName: "Frases claras e concisas",
    channel: "inline",
    markStyleClass: "mark-dashed",
    signal:
      "substantivo que nomeia uma ação, de uma lista curada, ligado por “de” a outro substantivo, ou vários deles na mesma frase",
    why:
      "Quando uma ação aparece como substantivo (“a análise”) em vez de verbo (“analisar”), pode ficar menos direto " +
      "perceber quem faz o quê. Várias dessas construções na mesma frase, ou uma ligada à outra por “de” (“a análise " +
      "da concessão”), podem tornar a leitura mais abstrata.",
  },
  jargon: {
    label: "Jargão",
    ruleId: "jargon",
    kind: "Escolha lexical",
    principleName: "Palavras familiares",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal: "termo escrito exatamente como está no glossário do Lucid (a expressão mais longa tem prioridade)",
    why: "Um termo pouco conhecido fora da área afasta o leitor que não é especialista.",
  },
  vocabulario_da_organizacao: {
    label: "Vocabulário da organização",
    ruleId: "vocabulario_da_organizacao",
    kind: "Escolha lexical",
    principleName: "Palavras familiares",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal: "termo escrito exatamente como a organização o declarou (a expressão mais longa tem prioridade)",
    why: "Um termo que o leitor não conhece trava a leitura. Quem sabe o que o leitor conhece é a organização, que declarou este termo; a norma não tem como saber.",
  },
  sigla_sem_expansao: {
    label: "Sigla sem expansão",
    ruleId: "sigla_sem_expansao",
    kind: "Escolha lexical",
    principleName: "Palavras familiares",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal:
      "sigla (de 2 a 6 letras maiúsculas) usada antes de ser escrita por extenso; ficam de fora siglas de estado, unidades de medida e siglas muito conhecidas",
    why: "Sigla não apresentada exige que o leitor já a conheça. Quem não conhece trava logo no começo.",
  },
  long_sentence: {
    label: "Comprimento de frase",
    ruleId: "long_sentence",
    kind: "Extensão da frase",
    principleName: "Frases concisas",
    channel: "passage",
    markStyleClass: "",
    signal: "frase com mais palavras do que o número definido no perfil editorial (parâmetro do Lucid)",
    why:
      "Frases longas tendem a acumular ideias. A norma pede uma ideia por frase e variação de tamanho, sem " +
      "fixar número. O comprimento é um motivo para reler a frase, não um defeito: uma frase longa com uma " +
      "ideia só pode estar adequada, e uma curta pode ser difícil por outros motivos.",
  },
  mais_que_perfeito_sintetico: {
    label: "Mais-que-perfeito sintético",
    ruleId: "mais_que_perfeito_sintetico",
    kind: "Tempo verbal",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dotted",
    signal:
      "forma verbal de uma lista de mais-que-perfeito (“fizera”, “dissera”), tirada do PortiLexicon-UD e sem as formas ambíguas",
    why: "Forma verbal pouco usada na fala (“fizera” em vez de “tinha feito”) e, por isso, mais difícil de ler.",
  },
  gerundismo: {
    label: "Gerundismo",
    ruleId: "gerundismo",
    kind: "Construção sintática",
    principleName: "Frases concisas",
    channel: "inline",
    markStyleClass: "mark-dashed",
    signal: "padrão “ir + estar + gerúndio” (ex.: “vai estar enviando”)",
    why: "Alonga a frase sem necessidade: a forma simples (“vai enviar”) é mais direta.",
  },
  adverbios_vagos: {
    label: "Advérbios vagos",
    ruleId: "adverbios_vagos",
    kind: "Escolha lexical",
    principleName: "Frases concisas",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal: "advérbio de reforço ou de atenuação de uma lista curada (basicamente, efetivamente, realmente…)",
    why: "Advérbio que reforça sem acrescentar: costuma sair sem mudar o que a frase afirma.",
  },
  adverbio_mente_denso: {
    label: "Advérbios em -mente (descontinuado)",
    ruleId: "adverbio_mente_denso",
    kind: "Escolha lexical",
    principleName: "Frases concisas",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal: "vários advérbios em -mente na mesma frase (lista tirada do PortiLexicon-UD)",
    why: "Muitos advérbios em -mente na mesma frase pesam a leitura. Critério descontinuado e desligado por padrão: “Advérbios vagos” o substitui.",
  },
  redundancia: {
    label: "Redundância",
    ruleId: "redundancia",
    kind: "Escolha lexical",
    principleName: "Frases concisas",
    channel: "inline",
    markStyleClass: "mark-solid",
    signal: "expressão de uma lista curada de pleonasmos e pares redundantes (“elo de ligação”)",
    why: "Um termo repete o sentido do outro sem acrescentar informação.",
  },
  perifrase_inflada: {
    label: "Perífrase inflada",
    ruleId: "perifrase_inflada",
    kind: "Escolha lexical",
    principleName: "Frases concisas",
    channel: "inline",
    markStyleClass: "mark-dashed",
    signal: "locução de uma lista curada que ocupa o lugar de uma preposição ou conjunção simples (“no sentido de”)",
    why: "Usa várias palavras onde uma simples bastaria.",
  },
  paragraph_length: {
    label: "Parágrafo longo",
    ruleId: "paragraph_length",
    kind: "Estrutura do documento",
    principleName: "Fácil de localizar",
    channel: "passage",
    markStyleClass: "",
    signal: "parágrafo com mais frases do que o número definido no perfil editorial (parâmetro do Lucid)",
    why: "Um bloco com muitas frases dificulta percorrer o texto e achar a informação.",
  },
  prose_enumeration: {
    label: "Enumeração em prosa",
    ruleId: "prose_enumeration",
    kind: "Estrutura do documento",
    principleName: "Fácil de localizar",
    channel: "passage",
    markStyleClass: "",
    signal:
      "marcadores de sequência diferentes no mesmo parágrafo, a partir do primeiro (“primeiro… segundo…”, “(1)… (2)…”), na quantidade mínima definida no perfil editorial",
    why: "Itens embutidos no texto corrido são mais difíceis de localizar do que numa lista.",
  },
  mesoclise: {
    label: "Mesóclise",
    ruleId: "mesoclise",
    kind: "Forma verbal",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dotted",
    signal: "pronome no meio do verbo, antes da terminação de futuro ou de condicional (“far-se-á”)",
    why: "Forma arcaica (“far-se-á”) e difícil de ler: a forma comum é mais direta.",
  },
  dupla_negacao: {
    label: "Dupla negação",
    ruleId: "dupla_negacao",
    kind: "Construção sintática",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dashed",
    signal: "expressão de uma lista curada que afirma negando o contrário (“não é incomum”)",
    why: "O leitor precisa desfazer a negação para chegar ao sentido afirmativo.",
  },
  subordinacao_densa: {
    label: "Subordinação densa",
    ruleId: "subordinacao_densa",
    kind: "Construção sintática",
    principleName: "Frases concisas",
    channel: "passage",
    markStyleClass: "",
    signal:
      "vários conectivos subordinativos na mesma frase (“que”, “porque”, “embora”, “para que”…), de uma lista curada",
    why: "Muitas orações subordinadas encadeadas prendem ideias demais numa frase só e pesam a leitura.",
  },
  leitor_terceira_pessoa: {
    label: "Fala indireta ao leitor",
    ruleId: "leitor_terceira_pessoa",
    kind: "Construção sintática",
    principleName: "Frases claras",
    channel: "inline",
    markStyleClass: "mark-dotted",
    signal:
      "palavra que nomeia o leitor (“o interessado”, “o cidadão”) como sujeito de um verbo de obrigação (“deve”, “deverá”), em palavras próximas",
    why: "Falar do leitor em terceira pessoa distancia. Dizer “você” aproxima e deixa claro quem deve agir.",
  },
  salto_de_nivel_titulo: {
    label: "Salto de nível de título",
    ruleId: "salto_de_nivel_titulo",
    kind: "Estrutura do documento",
    principleName: "Fácil de localizar",
    channel: "passage",
    markStyleClass: "",
    signal: "título que desce mais de um nível em relação ao título anterior (só quando o documento marca títulos)",
    why: "Saltos na hierarquia de títulos atrapalham quem lê pela estrutura: o sumário, a leitura rápida e o leitor de tela.",
  },
  long_heading: {
    label: "Título longo",
    ruleId: "long_heading",
    kind: "Estrutura do documento",
    principleName: "Fácil de localizar",
    channel: "passage",
    markStyleClass: "",
    signal:
      "título com mais palavras do que o limite do perfil editorial, com mais de uma frase ou terminado em ponto final (só quando o documento marca títulos)",
    why: "Um título serve de rótulo para localizar a seção. Longo ou em forma de frase, ele deixa de cumprir esse papel.",
  },
  single_item_list: {
    label: "Lista de um item",
    ruleId: "single_item_list",
    kind: "Estrutura do documento",
    principleName: "Fácil de localizar",
    channel: "passage",
    markStyleClass: "",
    signal: "lista com exatamente um item (só quando o documento marca listas)",
    why: "Uma lista serve para separar vários itens. Com um só, não ajuda a localizar nada e sugere que falta um item.",
  },
};
