import type { UiCriterionId } from "../locale/criteria";

export const CRITERION_ORDER: readonly UiCriterionId[] = [
  "passive_voice",
  "passiva_sintetica",
  "nominalization",
  "nominalizacao_encadeada",
  "hidden_verb",
  "mais_que_perfeito_sintetico",
  "gerundismo",
  "jargon",
  "vocabulario_da_organizacao",
  "organization_vocabulary",
  "sigla_sem_expansao",
  "undefined_acronym",
  "adverbios_vagos",
  "adverbio_mente_denso",
  "redundancia",
  "perifrase_inflada",
  "mesoclise",
  "dupla_negacao",
  "leitor_terceira_pessoa",
  "reader_in_third_person",
  "ambiguous_shall",
  "subordinacao_densa",
  "long_sentence",
  "paragraph_length",
  "prose_enumeration",
  "salto_de_nivel_titulo",
  "heading_level_skip",
  "long_heading",
  "single_item_list",
];
